--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PocketMusic/pocketmusic-addon-simplearea-legacy
build-by-default: true
branches:
- main
projects:
  PocketMusicAddonSimpleArea:
    path: addon/
...
